<a href="https://colab.research.google.com/github/sofiaKon/gradio-api-data-project/blob/main/newh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1: Compare Server Headers

In [28]:
import requests

naver_response = requests.get("https://www.naver.com")
print("Naver")
for key, value in naver_response.headers.items():
    print(f"{key}: {value}")

print("\n")

google_response = requests.get("https://www.google.com")
print("Google")
for key, value in google_response.headers.items():
    print(f"{key}: {value}")

print("\n")
compare_keys = ['Server', 'Content-Type', 'Content-Encoding']
for key in compare_keys:
    naver_val = naver_response.headers.get(key, " ")
    google_val = google_response.headers.get(key, " ")
    print(f"\n[{key}]")
    print(f"  네이버: {naver_val}")
    print(f"  구글:   {google_val}")

Naver
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
x-frame-options: DENY
x-xss-protection: 1; mode=block
strict-transport-security: max-age=63072000; includeSubdomains
referrer-policy: unsafe-url
Content-Encoding: gzip
Server: nfront
Content-Length: 36144
Date: Sun, 29 Mar 2026 05:33:20 GMT
Connection: keep-alive
Vary: Accept-Encoding


Google
Date: Sun, 29 Mar 2026 05:33:20 GMT
Expires: -1
Cache-Control: private, max-age=0
Content-Type: text/html; charset=ISO-8859-1
Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-t8d8d9yE24M2EqVuiY0uPw' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
Reporting-Endpoints: default="//www.google.com/httpservice/retry/jserror?ei=oLnIaYb0OO6FwbkP5sSOkQc&cad=crash&error=Page%20Crash&jsel=1&bver=2410&dpf=m93XdqkAp1JHd53EmhJMCCSa3J0y7g7-JWnqu55wwW4"
Accept-CH: Sec-CH-Prefers-Color-Scheme
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Encoding: gzip
Server: gws
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Set-Cookie: __Secure-STRP=AEEP7gIvevCh4bdJOlxM1kLfbtHZFZRDZp7GBpo9v40sD4nvD_yrO8GxWcAARRfftJ4YmBguAEY6vFaP5jEtTkA9gvE9j2okSEH2; expires=Sun, 29-Mar-2026 05:38:20 GMT; path=/; domain=.google.com; Secure; SameSite=strict, AEC=AaJma5tjvO4LweLvU5v-FnO7qcWGO3rq7GyfODPsXrc2YMXRVGHj5kmtpOs; expires=Fri, 25-Sep-2026 05:33:20 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=530=VOpFmBNoWFvjHk7ib5yphB1w4bWlBnht3xard2559CVTslrFNdpFBqq_2xUsYycO2K9gEOrLYo9zEu_2Edn5-No265exDiX0DOgavqIc4G8ShJ6eP1mslkXOGcZh0NMNusoIEM-nY7-49r9LaDhinXoNHmZjsAf7OqWS-wxe4nEjvPD80zplxwt5kdS_FsloHUcxGTuyXjJepprnLPdc45_jYMpiJfF4lkkZ80mToA; expires=Mon, 28-Sep-2026 05:33:20 GMT; path=/; domain=.google.com; HttpOnly, __Secure-BUCKET=CMYE; expires=Fri, 25-Sep-2026 05:33:20 GMT; path=/; domain=.google.com; Secure; HttpOnly
Transfer-Encoding: chunked



[Server]
  네이버: nfront
  구글:   gws

[Content-Type]
  네이버: text/html; charset=UTF-8
  구글:   text/html; charset=ISO-8859-1

[Content-Encoding]
  네이버: gzip
  구글:   gzip

In [29]:
urls = {
    "Naver": "https://www.naver.com",
    "Google": "https://www.google.com"
}

result = []

for name, url in urls.items():
    response = requests.get(url)
    result.append({
        "site": name,
        "url": url,
        "server_header": response.headers.get("Server", "Нет заголовка Server")
    })

df = pd.DataFrame(result)
print(df)

     site                     url server_header
0   Naver   https://www.naver.com        nfront
1  Google  https://www.google.com           gws

# Conlusion

Naver (nfront)
Naver uses nfront, which is part of its own server infrastructure, likely functioning as a frontend or CDN server.

Google (gws)
Google uses gws (Google Web Server), which is a proprietary web server developed by Google.

# Task 2: JSON → DataFrame

In [6]:
import requests
import pandas as pd

url = "https://jsonplaceholder.typicode.com/users"
response = requests.get(url)
data = response.json()

df = pd.DataFrame(data)
print("Main")
display(df)


address_df = pd.DataFrame(df['address'].tolist())
print("\n address Series → Data")
display(address_df)

Main

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

 address Series → Data

,street,suite,city,zipcode,geo
0,Kulas Light,Apt. 556,Gwenborough,92998-3874,"{'lat': '-37.3159', 'lng': '81.1496'}"
1,Victor Plains,Suite 879,Wisokyburgh,90566-7771,"{'lat': '-43.9509', 'lng': '-34.4618'}"
2,Douglas Extension,Suite 847,McKenziehaven,59590-4157,"{'lat': '-68.6102', 'lng': '-47.0653'}"
3,Hoeger Mall,Apt. 692,South Elvis,53919-4257,"{'lat': '29.4572', 'lng': '-164.2990'}"
4,Skiles Walks,Suite 351,Roscoeview,33263,"{'lat': '-31.8129', 'lng': '62.5342'}"
5,Norberto Crossing,Apt. 950,South Christy,23505-1337,"{'lat': '-71.4197', 'lng': '71.7478'}"
6,Rex Trail,Suite 280,Howemouth,58804-1099,"{'lat': '24.8918', 'lng': '21.8984'}"
7,Ellsworth Summit,Suite 729,Aliyaview,45169,"{'lat': '-14.3990', 'lng': '-120.7677'}"
8,Dayna Park,Suite 449,Bartholomebury,76495-3109,"{'lat': '24.6463', 'lng': '-168.8889'}"
9,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,"{'lat': '-38.2386', 'lng': '57.2232'}"

# Conclusion

In this task, I worked with JSON data retrieved from a web API and converted it into a structured Pandas DataFrame. I specifically focused on extracting the nested "address" field and transforming it into a separate, organized DataFrame.

This task helped me understand how to handle nested JSON data, perform data transformation, and structure complex information into a tabular format suitable for analysis.

# Task 3: Filter & Save Data

In [ ]:
url = "https://jsonplaceholder.typicode.com/posts"
data = requests.get(url).json()

df = pd.DataFrame(data)

df_even = df[df.index % 2 == 0]

df_even.to_excel("even_posts.xlsx", index=False)

print("File saved: even_posts.xlsx")

File saved: even_posts.xlsx

# Conclusion

The data was successfully retrieved from the given API and converted into a DataFrame.
Only rows with even indices (0, 2, 4, ...) were selected and saved into an Excel file.
This demonstrates how to filter data and export it into a structured file format for further use.

# Task 4: API + Gradio UI

In [1]:
import requests
import pandas as pd
import gradio as gr

def filter_by_userid(user_id):
    url = "https://jsonplaceholder.typicode.com/posts"
    params = {"userId": int(user_id)}
    response = requests.get(url, params=params)
    data = response.json()

    if not data:
        return pd.DataFrame({"Result": ["No data for this userId."]})

    df = pd.DataFrame(data)
    return df

demo = gr.Interface(
    fn=filter_by_userid,
    inputs=gr.Number(label="Enter userId (1-10)", precision=0),
    outputs="dataframe",
    title="Network & Web Data Collection Practice",
    description="Enter a userId to retrieve data for that user and display it as a Pandas DataFrame."
)

print("=" * 60)
print("Gradio UI is running!")
print("Click the link below to view the web data collection result.")
print("=" * 60)

demo.launch()

============================================================
Gradio UI is running!
Click the link below to view the web data collection result.
============================================================
It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://b65e63a6eae71fea1f.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

# Conclusion

The application successfully retrieves data from the API and dynamically filters it based on the user-provided userId.
By integrating Gradio, the system allows real-time interaction, and the filtered results are displayed in a Pandas DataFrame.
This demonstrates how to combine APIs, data processing, and user interfaces for interactive data analysis.

# Task 5: Data Analysis Project

In [8]:
from google.colab import files

uploaded = files.upload()

Saving 서울특별시 공공자전거 이용정보(일별)_2511.csv to 서울특별시 공공자전거 이용정보(일별)_2511 (1).csv
Saving 서울특별시 공공자전거 이용정보(일별)_2510.csv to 서울특별시 공공자전거 이용정보(일별)_2510 (1).csv
Saving 서울특별시 공공자전거 이용정보(일별)_2512.csv to 서울특별시 공공자전거 이용정보(일별)_2512 (1).csv

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import gradio as gr
import os


def read_csv_flexible(path):
    encodings = ["utf-8", "cp949", "euc-kr"]
    for enc in encodings:
        try:
            return pd.read_csv(path, encoding=enc)
        except:
            continue
    raise ValueError(f"Failed: {path}")

In [14]:
csv_files = [f for f in os.listdir() if f.endswith(".csv")]
csv_files

['서울특별시 공공자전거 이용정보(일별)_2511 (1).csv',
 '서울특별시 공공자전거 이용정보(일별)_2512 (1).csv',
 '서울특별시 공공자전거 이용정보(일별)_2510 (1).csv']

In [15]:
dfs = []
for f in csv_files:
    df = read_csv_flexible(f)
    df["source_file"] = f
    dfs.append(df)

len(dfs)

3

In [16]:
merged_df = pd.concat(dfs, ignore_index=True)
merged_df.shape

(5002107, 12)

In [17]:
merged_df.head()

,대여일자,대여소번호,대여소,대여구분코드,성별,연령대,이용건수,운동량,탄소량,이동거리(M),이용시간(분),source_file
0,2025-11-01,1965,1965. 삼환로즈빌아파트 105동 옆,정기권,NaN,~10대,1,11.64,0.17,734.98,3,서울특별시 공공자전거 이용정보(일별)_2511 (1).csv
1,2025-11-01,1160,1160. 양천향교역 7번출구앞,정기권,NaN,~10대,1,19.88,0.21,912.84,22,서울특별시 공공자전거 이용정보(일별)_2511 (1).csv
2,2025-11-01,1667,1667. 중계중학교,정기권,NaN,~10대,1,18.15,0.16,705.26,9,서울특별시 공공자전거 이용정보(일별)_2511 (1).csv
3,2025-11-01,1685,1685. 불암고등학교 앞 횡단보도,정기권,NaN,~10대,1,27.16,0.24,1055.35,7,서울특별시 공공자전거 이용정보(일별)_2511 (1).csv
4,2025-11-01,2618,2618. 삼전역 1번출구,정기권,NaN,~10대,1,36.30,0.38,1636.82,12,서울특별시 공공자전거 이용정보(일별)_2511 (1).csv

In [18]:
merged_df.columns.tolist()

['대여일자',
 '대여소번호',
 '대여소',
 '대여구분코드',
 '성별',
 '연령대',
 ' 이용건수',
 '운동량',
 '탄소량',
 '이동거리(M)',
 '이용시간(분)',
 'source_file']

In [19]:
summary_text = f"""
Rows: {len(merged_df)}
Columns: {len(merged_df.columns)}
Period files: {', '.join(csv_files)}
"""
print(summary_text)

Rows: 5002107
Columns: 12
Period files: 서울특별시 공공자전거 이용정보(일별)_2511 (1).csv, 서울특별시 공공자전거 이용정보(일별)_2512 (1).csv, 서울특별시 공공자전거 이용정보(일별)_2510 (1).csv

# Conclusion

In this project, I downloaded three CSV files containing daily public bike usage data from Seoul’s open data platform. After uploading the files to Google Colab, I successfully loaded them using the pandas library.

I then combined the datasets into a single table and performed basic data exploration. Specifically, I checked the number of rows and columns and reviewed the overall structure of the dataset.

# Task 6: Gemini API (AI Integration)

In [14]:
import google.generativeai as genai
import gradio as gr

In [15]:
genai.configure(api_key="YOUR_API_KEY")

In [20]:
model = genai.GenerativeModel("gemini-1.5-flash-latest")

In [21]:
def translate_first_line(text):
    try:
        if not text or not text.strip():
            return "Please enter text."

        first_line = text.strip().split("\n")[0]

        prompt = f"Translate this Korean text into English:\n{first_line}"

        response = model.generate_content(prompt)

        return response.text

    except Exception as e:
        return f"Error: {e}"

In [22]:
demo = gr.Interface(
    fn=translate_first_line,
    inputs=gr.Textbox(lines=4, label="Enter Task 7 Text"),
    outputs=gr.Textbox(label="Translation"),
    title="Task 9 - Gemini Translator",
    description="Translate only the first line of Task 7."
)

In [26]:
demo.launch()

Rerunning server... use `close()` to stop if you need to change `launch()` parameters.
----
It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://559e0f8121d9087645.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

# Conclusion

In this task, I developed a simple translation interface using the Gemini API and Gradio. The application takes the text of Task 7 as input and translates only the first line into English, as required.

I implemented a function that processes user input, extracts the first line, and sends it to the Gemini model for translation. The result is then displayed in a user-friendly interface.

This task helped me understand how to integrate a generative AI API into an interactive application and how to control the output based on specific requirements.